---
- name: Manage fedex OpenWrt
  hosts: fedex
  gather_facts: false

  vars_files:
      - vars/openwrt.yml

  pre_tasks:
      - name: Fedex | Check OpenWrt access
        community.openwrt.ping:

  tasks:
      - name: Fedex | Configure main settings
        ansible.builtin.import_tasks: tasks/main.yml

      - name: Fedex | Configure Bbox WAN
        ansible.builtin.import_tasks: tasks/wan.yml

      - name: Fedex | Configure temporary LAN
        ansible.builtin.import_tasks: tasks/temp_lan.yml

  handlers:
      - name: Fedex | Reload network
        community.openwrt.service:
            name: network
            state: reloaded

      - name: Fedex | Reload firewall
        community.openwrt.service:
            name: firewall
            state: reloaded

      - name: Fedex | Restart dnsmasq
        community.openwrt.service:
            name: dnsmasq
            state: restarted

      - name: Fedex | Restart dropbear
        community.openwrt.service:
            name: dropbear
            state: restarted

      - name: Fedex | Restart uhttpd
        community.openwrt.service:
            name: uhttpd
            state: restarted
