[project]
name = "homelab"
version = "0.0.0"
requires-python = "==3.14.6"

dependencies = [
	"ansible==13.8.0",
	"ansible-lint==26.6.0",
	"bcrypt==4.3.0",
	"cloudflare==4.3.1",    # linuxhq.cloudflare v2.0.7 requires <5
	"jmespath==1.1.0",
	"jq==1.12.0",
	"passlib[bcrypt]==1.7.4",
	"requests==2.34.2",
]
