---
- name: features | block_dot_doq | Configure rule | {{ firewall_zone.name | upper }}
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: "{{ firewall_feature_sections[firewall_feature_name] | format(firewall_zone.name) }}"
      value:
          src: "{{ firewall_zone.name }}"
          dest: wan
          proto: [tcp, udp]
          dest_port: "853"
          target: REJECT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall
