---
- name: features | router_management | Configure rule | {{ firewall_zone.name | upper }}
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: "{{ firewall_feature_sections[firewall_feature_name] | format(firewall_zone.name) }}"
      value:
          src: "{{ firewall_zone.name }}"
          proto: tcp
          dest_ip: "{{ firewall_gateway }}"
          dest_port: [22, 80, 443, 3000]
          target: ACCEPT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall
