---
- name: Manage Mycelium ICX through UART
  hosts: mycelium_uart
  gather_facts: false

  module_defaults:
      group/bofzilla.icx.all:
          enable_password: "{{ icx_enable_password }}"

  vars_files:
      - ../../.config/networks.yml
      - ../../.config/cabinet.yml

  tasks:
      - name: ICX | Configure system
        bofzilla.icx.system:
            hostname: mycelium
            save_when: changed

      - name: ICX | Configure management
        ansible.builtin.import_tasks: tasks/management.yml

      - name: ICX | Configure VLANs
        ansible.builtin.import_tasks: tasks/vlans.yml

      - name: ICX | Configure interfaces
        ansible.builtin.import_tasks: tasks/interfaces.yml
