---
- name: mdns | Configure Avahi reflector
  community.openwrt.template:
      src: avahi-daemon.conf.j2
      dest: /etc/avahi/avahi-daemon.conf
      owner: root
      group: root
      mode: "0644"
  notify: Fedex | Restart Avahi

- name: mdns | Keep Avahi reflector enabled
  community.openwrt.service:
      name: avahi-daemon
      enabled: true
      state: started
