---
- name: nut | Configure Eaton UPS
  community.openwrt.uci:
      command: section
      config: nut_server
      type: driver
      name: "{{ nut.ups.name }}"
      value:
          driver: "{{ nut.ups.driver }}"
          port: "{{ nut.ups.port }}"
          vendorid: "{{ nut.ups.vendorid }}"
          productid: "{{ nut.ups.productid }}"
      replace: true
      autocommit: true
  notify:
      - Fedex | Replay NUT USB hotplug
      - Fedex | Restart NUT server

- name: nut | Listen on internal interfaces
  community.openwrt.uci:
      command: section
      config: nut_server
      type: listen_address
      name: "{{ nut_listener.name }}"
      value:
          address: "{{ nut_listener.address }}"
          port: "{{ nut.listen_port }}"
      replace: true
      autocommit: true
  loop: "{{ nut.listeners }}"
  loop_control:
      label: "{{ nut_listener.name }}"
      loop_var: nut_listener
  notify: Fedex | Restart NUT server

- name: nut | Configure primary monitor user
  community.openwrt.uci:
      command: section
      config: nut_server
      type: user
      name: local_monitor
      value:
          username: "{{ nut.monitor.username }}"
          password: "{{ nut.monitor.password }}"
          upsmon: master
      replace: true
      autocommit: true
  no_log: true
  notify: Fedex | Restart NUT server

- name: nut | Configure monitor defaults
  community.openwrt.uci:
      command: section
      config: nut_monitor
      type: upsmon
      name: upsmon
      value:
          defaultnotify: SYSLOG
      replace: true
      autocommit: true
  notify: Fedex | Restart NUT monitor

- name: nut | Monitor Eaton UPS
  community.openwrt.uci:
      command: section
      config: nut_monitor
      type: master
      name: "{{ nut.ups.name }}"
      value:
          upsname: "{{ nut.ups.name }}"
          hostname: localhost
          powervalue: "1"
          username: "{{ nut.monitor.username }}"
          password: "{{ nut.monitor.password }}"
      replace: true
      autocommit: true
  no_log: true
  notify: Fedex | Restart NUT monitor

- name: nut | Enable services
  community.openwrt.service:
      name: "{{ nut_service }}"
      enabled: true
      state: started
  loop:
      - nut-server
      - nut-monitor
  loop_control:
      loop_var: nut_service
