---
- name: temp_lan | Configure temporary LAN
  community.openwrt.uci:
      command: section
      config: network
      type: interface
      name: lan
      value:
          device: "{{ temp_lan.device }}"
          proto: static
          ipaddr: "{{ temp_lan.ipaddr }}"
          netmask: "{{ temp_lan.netmask }}"
          delegate: "0"
      replace: true
      autocommit: true
  notify: Fedex | Reload network

- name: temp_lan | Configure temporary LAN DHCP
  community.openwrt.uci:
      command: section
      config: dhcp
      type: dhcp
      name: lan
      value:
          interface: lan
          start: "{{ temp_lan.dhcp_start }}"
          limit: "{{ temp_lan.dhcp_limit }}"
          leasetime: "{{ temp_lan.dhcp_leasetime }}"
          dhcp_option:
              - "6,{{ temp_lan.ipaddr }}"
      replace: true
      autocommit: true
  notify: Fedex | Restart dnsmasq
