---
- name: temp_lan | Configure temporary LAN
  community.openwrt.uci:
      command: section
      config: network
      type: interface
      name: lan
      value:
          device: "{{ temp_lan.device }}"
          proto: static
          ipaddr: "{{ temp_lan.ipaddr }}"
          netmask: "{{ temp_lan.netmask }}"
          delegate: "0"
      replace: true
      autocommit: true
  notify: Fedex | Reload network

- name: temp_lan | Configure temporary LAN DHCP
  community.openwrt.uci:
      command: section
      config: dhcp
      type: dhcp
      name: lan
      value:
          interface: lan
          start: "{{ temp_lan.dhcp_start }}"
          limit: "{{ temp_lan.dhcp_limit }}"
          leasetime: "{{ temp_lan.dhcp_leasetime }}"
      replace: true
      autocommit: true
  notify: Fedex | Restart dnsmasq

- name: temp_lan | Configure static DHCP hosts
  community.openwrt.uci:
      command: section
      config: dhcp
      type: host
      name: "{{ static_host.name }}"
      value:
          name: "{{ static_host.name }}"
          mac: "{{ static_host.mac }}"
          ip: "{{ static_host.ip }}"
          dns: "1"
      replace: true
      autocommit: true
  loop: "{{ temp_lan.static_hosts }}"
  loop_control:
      label: "{{ static_host.name }}"
      loop_var: static_host
  notify: Fedex | Restart dnsmasq

- name: temp_lan | Configure LAN firewall zone
  community.openwrt.uci:
      command: section
      config: firewall
      type: zone
      name: lan
      value:
          name: lan
          network: lan
          input: REJECT
          output: ACCEPT
          forward: REJECT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: temp_lan | Allow LAN DHCP
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: allow_lan_dhcp
      value:
          name: Allow-LAN-DHCP
          src: lan
          proto: udp
          src_port: "68"
          dest_port: "67"
          target: ACCEPT
          family: ipv4
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: temp_lan | Allow LAN DNS
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: allow_lan_dns
      value:
          name: Allow-LAN-DNS
          src: lan
          proto:
              - tcp
              - udp
          dest_port: "53"
          target: ACCEPT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: temp_lan | Allow LAN NUT status
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: allow_lan_nut
      value:
          name: Allow-LAN-NUT
          src: lan
          proto: tcp
          dest_port: "3493"
          target: ACCEPT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: temp_lan | Allow LAN to WAN
  community.openwrt.uci:
      command: section
      config: firewall
      type: forwarding
      name: lan_wan
      value:
          src: lan
          dest: wan
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall
