---
## ansible-galaxy install -f -r .config/requirements.yml
collections:
  - name: community.openwrt
    version: 1.6.0
  - name: linuxhq.cloudflare
    version: 2.1.6
  - name: moreati.jq
    version: 0.2.1
  - name: https://github.com/vic1707/ansible-collection-purelymail#ansible_collections/bofzilla/purelymail
    type: git
  - name: https://github.com/vic1707/ansible-collection-brocade-icx#ansible_collections/bofzilla/icx
    type: git
    version: 5631c64f2027c835c2eda07d25e4825da862930e
