---
## ansible-galaxy install -f -r .config/requirements.yml
collections:
  - name: community.openwrt
    version: 1.6.0
  - name: linuxhq.cloudflare
    version: 2.1.9
  - name: moreati.jq
    version: 0.2.1
  - name: https://github.com/vic1707/ansible-collection-purelymail#ansible_collections/bofzilla/purelymail
    type: git
  - name: https://github.com/vic1707/ansible-collection-brocade-icx#ansible_collections/bofzilla/icx
    type: git
    version: de31c9ee38a92cd0157aa69a31c8392dd8daddfe
