actionlint = "actionlint"

ansible-lint = "git ls-files -z | xargs -0 -r -t ansible-lint -c .config/.ansible-lint.yml -x yaml"
"ansible-lint:fix" = "ansible-lint -c .config/.ansible-lint.yml --fix"

ansible-syntax-check = "rg --files -g '*.playbook.yml' | xargs -r -t ansible-playbook --syntax-check"

shellcheck = "rg --ignore --hidden -l '^#!' . | xargs -r -t shellcheck -a -Calways"

shfmt = "shfmt -d --apply-ignore -s -bn -ci -sr -kp ."
"shfmt:fix" = "shfmt -w --apply-ignore -s -bn -ci -sr -kp ."

typos = "typos -c .config/.typos.toml"

zizmor = "zizmor ."


[format]
depends = ["shfmt"]

["format:fix"]
depends = ["shfmt:fix"]

[ci-lint]
depends = ["zizmor", "actionlint"]

[lint]
depends = ["ansible-lint", "ansible-syntax-check", "typos", "shellcheck"]

["lint:fix"]
depends = ["ansible-lint:fix"]
