actionlint = "actionlint"

ansible-lint = "ansible-lint -c .config/.ansible-lint.yml"
"ansible-lint:fix" = "ansible-lint -c .config/.ansible-lint.yml --fix"

shellcheck = "rg --ignore --hidden -l '^#!' . | xargs -r -t shellcheck -a -Calways"

shfmt = "shfmt -d --apply-ignore -s -bn -ci -sr -kp ."
"shfmt:fix" = "shfmt -w --apply-ignore -s -bn -ci -sr -kp ."

typos = "typos -c .config/.typos.toml"

zizmor = "zizmor ."


[format]
depends = ["shfmt"]

["format:fix"]
depends = ["shfmt:fix"]

[ci-lint]
depends = ["zizmor", "actionlint"]

[lint]
depends = ["ansible-lint", "typos", "shellcheck"]

["lint:fix"]
depends = ["ansible-lint:fix"]
