---
- name: Rotate Hydra BMC password
  hosts: hydra_ipmi
  connection: local
  gather_facts: false

  vars_files:
      - vars/ipmi.yml

  vars:
      ipmi_old_password: "{{ lookup('env', 'HYDRA_IPMI_OLD_PASSWORD') | trim }}"

  module_defaults:
      community.general.redfish_command:
          baseuri: "{{ ansible_host }}"
          username: "{{ ipmi_username }}"
          password: "{{ ipmi_old_password }}"
          validate_certs: false
      community.general.redfish_info:
          baseuri: "{{ ansible_host }}"
          username: "{{ ipmi_username }}"
          password: "{{ ipmi_password }}"
          validate_certs: false

  pre_tasks:
      - name: Hydra IPMI password | Validate passwords
        ansible.builtin.assert:
            that:
                - ipmi_old_password | length > 0
                - ipmi_password | length >= 12
                - ipmi_password | length <= 20
                - ipmi_old_password != ipmi_password
            fail_msg: >-
                Update the desired SOPS password, then set HYDRA_IPMI_OLD_PASSWORD to the current password.
        no_log: true

  tasks:
      - name: Hydra IPMI password | Update administrator password
        community.general.redfish_command:
            category: Accounts
            command: [UpdateUserPassword]
            new_username: "{{ ipmi_username }}"
            new_password: "{{ ipmi_password }}"
        no_log: true

      - name: Hydra IPMI password | Verify new password
        community.general.redfish_info:
            category: [Accounts]
            command: [ListUsers]
        no_log: true
