---
- name: vlans | Configure active Mycelium VLANs
  bofzilla.icx.vlans:
      vlans: "{{ active_networks | icx_vlans }}"
      purge: false
      save_when: changed

- name: vlans | Configure in-band management address
  bofzilla.icx.ve_interfaces:
      interfaces: "{{ active_networks | icx_ve_interfaces }}"
      save_when: changed
