---
- name: policies | client | Configure firewall zone
  community.openwrt.uci:
      command: section
      config: firewall
      type: zone
      name: "{{ firewall_zone.name }}"
      value:
          name: "{{ firewall_zone.name }}"
          network: "{{ firewall_zone.members }}"
          input: REJECT
          output: ACCEPT
          forward: REJECT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: policies | client | Allow DHCP
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: "allow_{{ firewall_zone.name }}_dhcp"
      value:
          name: "Allow-{{ firewall_zone.name | upper }}-DHCP"
          src: "{{ firewall_zone.name }}"
          proto: udp
          src_port: "68"
          dest_port: "67"
          target: ACCEPT
          family: ipv4
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: policies | client | Allow DNS
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: "allow_{{ firewall_zone.name }}_dns"
      value:
          name: "Allow-{{ firewall_zone.name | upper }}-DNS"
          src: "{{ firewall_zone.name }}"
          proto:
              - tcp
              - udp
          dest_ip: "{{ firewall_zone.gateway }}"
          dest_port: "53"
          target: ACCEPT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: policies | client | Allow NUT status
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: "allow_{{ firewall_zone.name }}_nut"
      value:
          name: "Allow-{{ firewall_zone.name | upper }}-NUT"
          src: "{{ firewall_zone.name }}"
          proto: tcp
          dest_ip: "{{ firewall_zone.gateway }}"
          dest_port: "3493"
          target: ACCEPT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall
  when: firewall_zone.allow_nut | default(false)

- name: policies | client | Allow NTP
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: "allow_{{ firewall_zone.name }}_ntp"
      value:
          name: "Allow-{{ firewall_zone.name | upper }}-NTP"
          src: "{{ firewall_zone.name }}"
          proto: udp
          dest_ip: "{{ firewall_zone.gateway }}"
          dest_port: "123"
          target: ACCEPT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall
  when: firewall_zone.allow_ntp | default(false)

- name: policies | client | Allow ping
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: "allow_{{ firewall_zone.name }}_ping"
      value:
          name: "Allow-{{ firewall_zone.name | upper }}-Ping"
          src: "{{ firewall_zone.name }}"
          proto: icmp
          dest_ip: "{{ firewall_zone.gateway }}"
          icmp_type: echo-request
          target: ACCEPT
          family: ipv4
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: policies | client | Redirect DNS to AdGuard Home
  community.openwrt.uci:
      command: section
      config: firewall
      type: redirect
      name: "redirect_{{ firewall_zone.name }}_dns"
      value:
          name: "Redirect-{{ firewall_zone.name | upper }}-DNS"
          src: "{{ firewall_zone.name }}"
          proto:
              - tcp
              - udp
          src_dport: "53"
          dest_port: "53"
          target: DNAT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: policies | client | Block encrypted DNS bypass
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: "block_{{ firewall_zone.name }}_dot"
      value:
          name: "Block-{{ firewall_zone.name | upper }}-DoT-DoQ"
          src: "{{ firewall_zone.name }}"
          dest: wan
          proto:
              - tcp
              - udp
          dest_port: "853"
          target: REJECT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall
  when: firewall_zone.allow_wan | default(false)

- name: policies | client | Allow WAN access
  community.openwrt.uci:
      command: section
      config: firewall
      type: forwarding
      name: "{{ firewall_zone.name }}_wan"
      value:
          src: "{{ firewall_zone.name }}"
          dest: wan
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall
  when: firewall_zone.allow_wan | default(false)
