---
- name: policies | mgmt | Configure firewall zone | {{ firewall_zone.name | upper }}
  community.openwrt.uci:
      command: section
      config: firewall
      type: zone
      name: "{{ firewall_zone.name }}"
      value:
          name: "{{ firewall_zone.name }}"
          network: "{{ firewall_zone.members }}"
          input: REJECT
          output: ACCEPT
          forward: REJECT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: policies | mgmt | Allow rescue forwarding | {{ firewall_zone.name | upper }}
  community.openwrt.uci:
      command: section
      config: firewall
      type: forwarding
      name: rescue_mgmt
      value:
          src: rescue
          dest: mgmt
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: policies | mgmt | Allow DHCP | {{ firewall_zone.name | upper }}
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: allow_mgmt_dhcp
      value:
          name: Allow-MGMT-DHCP
          src: mgmt
          proto: udp
          src_port: "68"
          dest_port: "67"
          target: ACCEPT
          family: ipv4
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: policies | mgmt | Allow DNS | {{ firewall_zone.name | upper }}
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: allow_mgmt_dns
      value:
          name: Allow-MGMT-DNS
          src: mgmt
          proto:
              - tcp
              - udp
          dest_ip: "{{ mgmt_network.gateway }}"
          dest_port: "53"
          target: ACCEPT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: policies | mgmt | Allow router management | {{ firewall_zone.name | upper }}
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: allow_mgmt_router
      value:
          name: Allow-MGMT-Router
          src: mgmt
          proto: tcp
          dest_ip: "{{ mgmt_network.gateway }}"
          dest_port: "22 80 443"
          target: ACCEPT
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall

- name: policies | mgmt | Allow ping | {{ firewall_zone.name | upper }}
  community.openwrt.uci:
      command: section
      config: firewall
      type: rule
      name: allow_mgmt_ping
      value:
          name: Allow-MGMT-Ping
          src: mgmt
          proto: icmp
          dest_ip: "{{ mgmt_network.gateway }}"
          icmp_type: echo-request
          target: ACCEPT
          family: ipv4
      replace: true
      autocommit: true
  notify: Fedex | Reload firewall
