---
- name: bmc | Check custom administrator credentials
  community.general.redfish_info:
      category: [Accounts]
      command: [ListUsers]
  register: ipmi_administrator_access
  failed_when: false
  no_log: true

- name: bmc | Create custom administrator in its fixed slot
  community.general.redfish_command:
      username: "{{ ipmi_factory_username }}"
      password: "{{ ipmi_factory_password }}"
      category: Accounts
      command: [AddUser]
      id: "{{ ipmi_administrator_id }}"
      new_username: "{{ ipmi_username }}"
      new_password: "{{ ipmi_password }}"
      roleid: Administrator
  when: ipmi_administrator_access.redfish_facts is not defined
  no_log: true

- name: bmc | Create operator accounts in fixed slots
  community.general.redfish_command:
      category: Accounts
      command: [AddUser]
      id: "{{ ipmi_account.id }}"
      new_username: "{{ ipmi_account.username }}"
      new_password: "{{ ipmi_account.password }}"
      roleid: Operator
  loop: "{{ ipmi_accounts }}"
  loop_control:
      label: "{{ ipmi_account.username }}"
      loop_var: ipmi_account
  no_log: true

- name: bmc | Configure account lockout
  community.general.redfish_command:
      category: Accounts
      command: [UpdateAccountServiceProperties]
      account_properties:
          AccountLockoutThreshold: 5
          AccountLockoutDuration: 600

- name: bmc | Configure manager NIC
  community.general.redfish_config:
      category: Manager
      command: [SetManagerNic]
      nic_addr: "AC:1F:6B:E6:76:D2"
      nic_config:
          DHCPv4:
              DHCPEnabled: true

- name: bmc | Configure network services
  community.general.redfish_config:
      category: Manager
      command: [SetNetworkProtocols]
      network_protocols:
          HTTP:
              ProtocolEnabled: false
          HTTPS:
              ProtocolEnabled: true
          SSH:
              ProtocolEnabled: false
          SSDP:
              ProtocolEnabled: false
          SNMP:
              ProtocolEnabled: false
          NTP:
              ProtocolEnabled: true
              NTPServers:
                  - 0.pool.ntp.org
                  - 1.pool.ntp.org
