---
- name: validate-credentials | Validate BMC usernames and passwords
  ansible.builtin.assert:
      that:
          - bmc_username_lengths | min > 0
          - bmc_usernames | unique | length == bmc_usernames | length
          - bmc_passwords | unique | length == bmc_passwords | length
          - bmc_password_lengths | min >= 12
          - bmc_password_lengths | max <= 16
          - >-
              bmc_passwords
              | select('match', '.*[A-Z].*')
              | length == bmc_passwords | length
          - >-
              bmc_passwords
              | select('match', '.*[a-z].*')
              | length == bmc_passwords | length
          - >-
              bmc_passwords
              | select('match', '.*[0-9].*')
              | length == bmc_passwords | length
          - >-
              bmc_passwords
              | select('match', '^[A-Za-z0-9]+$')
              | length == bmc_passwords | length
      fail_msg: >-
          BMC usernames and passwords must be unique; passwords must contain
          12-16 alphanumeric characters including uppercase, lowercase, and digits.
  vars:
      bmc_username_lengths: "{{ bmc_usernames | map('length') | list }}"
      bmc_password_lengths: "{{ bmc_passwords | map('length') | list }}"
  no_log: true
  tags: always
